services:
  postgres-linkwarden:
    image: postgres:16-alpine
    env_file: .env
    restart: always
    volumes:
      - /${DOCKER_VOLUME_STORAGE:-/var/docker/appdata}/linkwarden/pgdata:/var/lib/postgresql/data
  linkwarden:
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: always
    build: . # uncomment to build from source
    #image: ghcr.io/linkwarden/linkwarden:latest # comment to build from source
    ports:
      - 3000:3000
    volumes:
      - /${DOCKER_VOLUME_STORAGE:-/var/docker/appdata}/linkwarden/data:/data/data
    depends_on:
      - postgres
      - meilisearch
    networks:
      - cloud
      - linkwarden-net
  meilisearch-linkwarden:
    image: getmeili/meilisearch:v1.12.8
    restart: always
    env_file:
      - .env
    volumes:
      - /${DOCKER_VOLUME_STORAGE:-/var/docker/appdata}/linkwarden/meili_data:/meili_data
networks:
  linkwarden-net:
  cloud:
    external: true
    name: cloud-shared
